[build-system]
requires = ["setuptools>=61.0"] # Or another build backend like "hatchling" or "flit_core"
build-backend = "setuptools.build_meta" # Corresponds to the chosen build backend

[project]
name = "scratch-ml"
version = "0.1.0"
description = "Sandbox environment for experimenting with time series modeling and Ray Train/Tune, MLflow, and ONNX integration."
authors = [
    { name = "Syam Evani", email = "syamevani@gmail.com" },
]
license = { text = "MIT" } # Or a more specific license like { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.12" # Specify compatible Python versions
dependencies = [
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.6",
    "mlflow>=3.4.0",
    "numpy>=2.3.3",
    "onnx>=1.19.1",
    "onnxruntime-gpu>=1.23.0",
    "onnxscript>=0.5.3",
    "pandas>=2.3.2",
    "pip-tools>=7.5.0",
    "pre-commit>=4.5.1",
    "ray[default,train,tune]>=2.49.2",
    "ruff>=0.14.10",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.2",
    "tensorboard>=2.20.0",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]

[project.scripts]
# command = "module:function"
myproject-cli = "myproject.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
target-version = "py312"
line-length = 200
exclude = ["*.ipynb"]

[tool.ruff.lint]
select = [
  "E",   # general pep8 error rules (formatting)
  "F",   # pyflakes (logic/correctness)
  "B",   # bugbear (logic traps)
  "I",   # isort-like import rules (import org)
  "UP",  # pyupgrade (modern syntax)
  "ANN", # type annotation rules
]

ignore = [
  "E203", # makes it compat with Black-style slicing
  "E501", # ignore line length
]

[tool.ruff.lint.isort]
known-first-party = ["nfl"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
